#
# Module manifest for "VMXToolkit"
#
# Generated by: Graeme Meyer
#
# Generated on: 2020-01-25
#


@{
# The script or binary module file associated with this manifest
RootModule = 'vmxtoolkit.psm1'

# ModuletoProcess = 'vmxtoolkit.psm1'

# The version number of this module
ModuleVersion = '4.5.3.1'

# ID to uniquely identify this module
GUID = 'abe3797c-5a42-4e80-a1fb-9e648872ee14'

# Author of this module
Author = 'Karsten Bott'

# Company or manufacturer of this module
CompanyName = 'labbuildr'

# Copyright statement for this module
Copyright = '(c) 2014 Karsten Bott. Alle Rechte vorbehalten.
      Copyright 2014 Karsten Bott

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

'

# Description of the functionality provided by this module
Description = 'Powershell Modules for VMware Workstation on Windows/Linux and VMware Fusion on OSX, see https://github.com/bottkars/vmxtoolkit for details'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @(".\vmxtoolkitinit.ps1")

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @(
'.\Formats\vmxtoolkit.virtualmachine.Format.ps1xml',
'.\Formats\vmxtoolkit.virtualmachineinfo.Format.ps1xml',
'.\Formats\vmxtoolkit.vmxscsidisk.Format.ps1xml',
'.\Formats\vmxtoolkit.vmxsharedFolder.Format.ps1xml'
)

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @("vmxtoolkitinit.ps1",
"vmxtoolkit.psd1",
"vmxtoolkit.psm1")

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = 'vmx'